apiVersion: apps/v1
kind: Deployment
metadata:
  name: middle
  labels:
    name: middle 
spec:
  strategy: 
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: middle
  template:
    metadata:
      labels:
        app: middle
    spec:
      containers:
      - name: middle
        image: kontinu/nodejs-expert:v1.0
        resources: {}
        ports:
          - containerPort: 8080
            name: web
        env:
          - name: NEXT_URL
            value : "http://back/api"

---

apiVersion: v1
kind: Service
metadata:
  name: middle
spec:
  selector:
    app: middle
  type: NodePort
  ports:
  - name: http
    nodePort: 31003
    port: 80
    targetPort: web

