apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: us-east-2

nodeGroups:
  - name: nodegroup-1
    instanceType: t2.small
    desiredCapacity: 1

# eksctl create cluster  -f kubernetes/cluster.yaml
# eksctl utils write-kubeconfig --cluster=basic-cluster --kubeconfig=/tmp/config
